blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/dominikmodrzejewski99/ngx-signal-datetimepicker/discussions
    about: Have a question or want to discuss an idea? Start a Discussion instead of an Issue.
